list_users:
    path: /
    controller: App\Checking\User\Infrastructure\EntryPoint\Api\ListUsers\ListUsersApiAction
    methods: [GET]
    
create_user:
    path: /
    controller: App\Checking\User\Infrastructure\EntryPoint\Api\CreateUser\CreateUserApiAction
    methods: [POST]

update_user:
    path: /{id}/
    controller: App\Checking\User\Infrastructure\EntryPoint\Api\UpdateUser\UpdateUserApiAction
    methods: [PUT]
    
delete_user:
    path: /{id}/
    controller: App\Checking\User\Infrastructure\EntryPoint\Api\DeleteUser\DeleteUserApiAction
    methods: [DELETE]
